language: haxe

haxe:
  - "3.4.2"
  - development

dist: trusty
sudo: false

install:
  - yes | haxelib install all --always
  - npm install -g less
  - npm install -g less-plugin-clean-css
  - haxe CodeCookBook-neko.hxml

script:
  - bash -v deploy.sh

notifications:
  email: false
