language: haxe

haxe:
  - "3.2.1"
  - development

install:
  - yes | haxelib install CodeCookBook.hxml
  - haxe CodeCookBook.hxml
  - npm install -g less
  - npm install -g less-plugin-clean-css
  - lessc assets/includes/css/github.css assets/includes/css/github.min.css --clean-css="--s1 --advanced"
  - lessc assets/includes/css/haxe-nav.css assets/includes/css/haxe-nav.min.css --clean-css="--s1 --advanced"
  - lessc assets/includes/css/styles.css assets/includes/css/styles.min.css --clean-css="--s1 --advanced"
  - mkdir output
  - neko CodeCookBook.n

script:
  - bash -v deploy.sh

notifications:
  email: false
